# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import recommend_service_pb2 as recommend__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in recommend_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiRecommendServiceStub(object):
    """ĐỊNH NGHĨA DỊCH VỤ
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrainModel = channel.unary_unary(
                '/recommend_system.AiRecommendService/TrainModel',
                request_serializer=recommend__service__pb2.TrainRequest.SerializeToString,
                response_deserializer=recommend__service__pb2.TrainResponse.FromString,
                _registered_method=True)
        self.PredictRecommendation = channel.unary_unary(
                '/recommend_system.AiRecommendService/PredictRecommendation',
                request_serializer=recommend__service__pb2.PredictRequest.SerializeToString,
                response_deserializer=recommend__service__pb2.PredictResponse.FromString,
                _registered_method=True)


class AiRecommendServiceServicer(object):
    """ĐỊNH NGHĨA DỊCH VỤ
    """

    def TrainModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictRecommendation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiRecommendServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrainModel': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainModel,
                    request_deserializer=recommend__service__pb2.TrainRequest.FromString,
                    response_serializer=recommend__service__pb2.TrainResponse.SerializeToString,
            ),
            'PredictRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictRecommendation,
                    request_deserializer=recommend__service__pb2.PredictRequest.FromString,
                    response_serializer=recommend__service__pb2.PredictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommend_system.AiRecommendService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommend_system.AiRecommendService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiRecommendService(object):
    """ĐỊNH NGHĨA DỊCH VỤ
    """

    @staticmethod
    def TrainModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommend_system.AiRecommendService/TrainModel',
            recommend__service__pb2.TrainRequest.SerializeToString,
            recommend__service__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommend_system.AiRecommendService/PredictRecommendation',
            recommend__service__pb2.PredictRequest.SerializeToString,
            recommend__service__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
