# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommend_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'recommend_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17recommend_service.proto\x12\x10recommend_system\"B\n\x0bInteraction\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\x05\x12\x0e\n\x06rating\x18\x03 \x01(\x02\";\n\x0cTrainRequest\x12+\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1d.recommend_system.Interaction\"B\n\rTrainResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x03 \x01(\t\"0\n\x0ePredictRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\r\n\x05top_n\x18\x02 \x01(\x05\"T\n\x0fPredictResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1f\n\x17recommended_product_ids\x18\x03 \x03(\x05\x32\xc5\x01\n\x12\x41iRecommendService\x12O\n\nTrainModel\x12\x1e.recommend_system.TrainRequest\x1a\x1f.recommend_system.TrainResponse\"\x00\x12^\n\x15PredictRecommendation\x12 .recommend_system.PredictRequest\x1a!.recommend_system.PredictResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommend_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTERACTION']._serialized_start=45
  _globals['_INTERACTION']._serialized_end=111
  _globals['_TRAINREQUEST']._serialized_start=113
  _globals['_TRAINREQUEST']._serialized_end=172
  _globals['_TRAINRESPONSE']._serialized_start=174
  _globals['_TRAINRESPONSE']._serialized_end=240
  _globals['_PREDICTREQUEST']._serialized_start=242
  _globals['_PREDICTREQUEST']._serialized_end=290
  _globals['_PREDICTRESPONSE']._serialized_start=292
  _globals['_PREDICTRESPONSE']._serialized_end=376
  _globals['_AIRECOMMENDSERVICE']._serialized_start=379
  _globals['_AIRECOMMENDSERVICE']._serialized_end=576
# @@protoc_insertion_point(module_scope)
